baseURL = "https://4ug-aug.github.io/ComSocWeb/"
title = "Temporal keyword analysis"
description = "This project examines the development of the keyword Artificial Intelligence across research papers from 1990 to 2023."
relativeURLs = true
theme = "theme"
[params]
    authors = ["Asbjørn Magnussen s183546", "Eigil Albek s201030", "August Tollerup s204139"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://4ug-aug.github.io/ComSocWeb/"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

